#!/bin/bash
# install.sh - One-shot installer for LibraFlux on AlmaLinux 8, 9, 10
# Usage: curl -fsSL https://raw.githubusercontent.com/YOUR_ORG/LibraFlux/main/Deployment/install.sh | sudo bash
#        curl -fsSL https://raw.githubusercontent.com/YOUR_ORG/LibraFlux/main/Deployment/install.sh | sudo bash -s -- --skip-frr
#
# Tested on: AlmaLinux 8, 9, 10, Rocky Linux 8, 9, RHEL 8, 9, Ubuntu 22.04+, Debian 12+

set -euo pipefail

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------
GITHUB_REPO="${GITHUB_REPO:-malindarathnayake/LibraFlux}"
GITHUB_RELEASE="${GITHUB_RELEASE:-latest}"
LBCTL_BIN="${LBCTL_BIN:-/usr/local/bin/lbctl}"
LBCTL_CONFIG_DIR="${LBCTL_CONFIG_DIR:-/etc/lbctl}"
LBCTL_STATE_DIR="${LBCTL_STATE_DIR:-/var/lib/lbctl}"
MODULES_LOAD_CONF="/etc/modules-load.d/ipvs.conf"
SYSCTL_CONF="/etc/sysctl.d/90-lbctl.conf"

DRY_RUN=false
SKIP_FRR=false
SKIP_FRR_START=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "${BLUE}[STEP]${NC} $*"; }

run() {
    if $DRY_RUN; then
        echo "[DRY-RUN] $*"
    else
        "$@"
    fi
}

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_ID="${ID:-unknown}"
        OS_VERSION="${VERSION_ID:-unknown}"
        OS_VERSION_MAJOR="${VERSION_ID%%.*}"
    else
        OS_ID="unknown"
        OS_VERSION="unknown"
        OS_VERSION_MAJOR="unknown"
    fi
    log_info "Detected OS: $OS_ID $OS_VERSION"
}

check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

is_container() {
    [ -f /.dockerenv ] || grep -q 'docker\|lxc\|containerd' /proc/1/cgroup 2>/dev/null
}

# ------------------------------------------------------------------------------
# IPVS Kernel Modules
# ------------------------------------------------------------------------------
install_ipvs_modules() {
    log_step "Configuring IPVS kernel modules..."

    local modules="ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh"

    # Ensure directory exists
    run mkdir -p "$(dirname "$MODULES_LOAD_CONF")"

    # Create modules-load.d config
    run tee "$MODULES_LOAD_CONF" > /dev/null <<EOF
# lbctl - IPVS kernel modules
ip_vs
ip_vs_rr
ip_vs_wrr
ip_vs_sh
EOF

    # Load modules now (skip in container)
    if is_container; then
        log_info "Running in container - skipping module loading (host-level operation)"
    else
        for mod in $modules; do
            if ! lsmod | grep -q "^${mod}"; then
                log_info "Loading module: $mod"
                run modprobe "$mod" || log_warn "Failed to load $mod (may need reboot)"
            else
                log_info "Module already loaded: $mod"
            fi
        done
    fi

    # Install ipvsadm for debugging
    case "$OS_ID" in
        almalinux|rocky|rhel|centos|fedora)
            if ! command -v ipvsadm &> /dev/null; then
                log_info "Installing ipvsadm..."
                run dnf install -y ipvsadm
            fi
            ;;
        ubuntu|debian)
            if ! command -v ipvsadm &> /dev/null; then
                log_info "Installing ipvsadm..."
                run apt-get update
                run apt-get install -y ipvsadm
            fi
            ;;
    esac
}

# ------------------------------------------------------------------------------
# Sysctl Configuration
# ------------------------------------------------------------------------------
configure_sysctl() {
    log_step "Configuring sysctl parameters..."

    # Ensure directory exists
    run mkdir -p "$(dirname "$SYSCTL_CONF")"

    run tee "$SYSCTL_CONF" > /dev/null <<EOF
# lbctl - IPVS and networking tuning
# Generated by install.sh

# Enable IP forwarding (required for IPVS)
net.ipv4.ip_forward = 1

# IPVS connection tracking (required for NAT mode)
net.ipv4.vs.conntrack = 1

# Connection table size (tune for expected connections)
net.ipv4.vs.conn_tab_bits = 12

# Expire quiescent connections (backends set to weight 0)
net.ipv4.vs.expire_quiescent_template = 1

# Timeouts (seconds)
net.ipv4.vs.timeout_tcp = 900
net.ipv4.vs.timeout_tcpfin = 120
net.ipv4.vs.timeout_udp = 300

# Ignore ARP for VIPs on non-VIP interfaces (for DR mode)
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2

# Conntrack tuning
net.netfilter.nf_conntrack_max = 1048576
EOF

    # Apply sysctl (skip in container)
    if is_container; then
        log_info "Running in container - skipping sysctl apply (host-level operation)"
    else
        run sysctl --system > /dev/null 2>&1 || log_warn "Some sysctl parameters may not apply until reboot"
    fi
}

# ------------------------------------------------------------------------------
# FRR Installation
# ------------------------------------------------------------------------------
install_frr() {
    if $SKIP_FRR; then
        log_info "Skipping FRR installation (--skip-frr)"
        return
    fi

    log_step "Installing FRR for VRRP support..."

    case "$OS_ID" in
        almalinux|rocky|rhel|centos)
            # Enable EPEL if not present
            if ! rpm -q epel-release &> /dev/null; then
                log_info "Installing EPEL repository..."
                run dnf install -y epel-release
            fi
            
            # Install FRR
            if ! rpm -q frr &> /dev/null; then
                run dnf install -y frr
                run dnf install -y frr-pythontools 2>/dev/null || log_warn "frr-pythontools not available (optional)"
            else
                log_info "FRR already installed"
            fi
            ;;

        fedora)
            if ! rpm -q frr &> /dev/null; then
                run dnf install -y frr
                run dnf install -y frr-pythontools 2>/dev/null || log_warn "frr-pythontools not available (optional)"
            else
                log_info "FRR already installed"
            fi
            ;;

        ubuntu|debian)
            if ! dpkg -l frr &> /dev/null 2>&1; then
                # Add FRR repository for latest version
                run apt-get update
                run apt-get install -y curl gnupg lsb-release

                # FRR official repo
                curl -s https://deb.frrouting.org/frr/keys.gpg | gpg --dearmor -o /usr/share/keyrings/frr.gpg 2>/dev/null || true

                CODENAME=$(lsb_release -cs)
                echo "deb [signed-by=/usr/share/keyrings/frr.gpg] https://deb.frrouting.org/frr $CODENAME frr-stable" | \
                    tee /etc/apt/sources.list.d/frr.list > /dev/null

                run apt-get update
                run apt-get install -y frr frr-pythontools
            else
                log_info "FRR already installed"
            fi
            ;;

        *)
            log_warn "Unknown OS '$OS_ID' - skipping FRR installation"
            log_warn "Please install FRR manually: https://docs.frrouting.org/en/latest/installation.html"
            return
            ;;
    esac

    # Enable VRRP daemon
    configure_frr_daemons
}

configure_frr_daemons() {
    log_info "Enabling FRR VRRP daemon..."

    local frr_daemons="/etc/frr/daemons"
    
    if [ -f "$frr_daemons" ]; then
        # Enable vrrpd
        if grep -q "^vrrpd=no" "$frr_daemons"; then
            run sed -i 's/^vrrpd=no/vrrpd=yes/' "$frr_daemons"
            log_info "Enabled vrrpd in $frr_daemons"
        elif grep -q "^vrrpd=yes" "$frr_daemons"; then
            log_info "vrrpd already enabled"
        else
            echo "vrrpd=yes" | run tee -a "$frr_daemons" > /dev/null
        fi
    else
        log_warn "FRR daemons file not found at $frr_daemons"
    fi

    # Start FRR
    if ! $SKIP_FRR_START; then
        log_info "Starting FRR service..."
        run systemctl enable frr
        run systemctl restart frr
    else
        log_info "Skipping FRR start (--skip-frr-start)"
    fi
}

# ------------------------------------------------------------------------------
# Download Latest Release
# ------------------------------------------------------------------------------
download_lbctl_binary() {
    log_step "Downloading lbctl binary from GitHub..."

    local arch
    arch=$(uname -m)
    
    case "$arch" in
        x86_64)
            arch="amd64"
            ;;
        aarch64|arm64)
            arch="arm64"
            ;;
        *)
            log_error "Unsupported architecture: $arch"
            exit 1
            ;;
    esac

    local os="linux"
    local binary_name="lbctl-${os}-${arch}"
    local download_url

    if [ "$GITHUB_RELEASE" = "latest" ]; then
        download_url="https://github.com/${GITHUB_REPO}/releases/latest/download/${binary_name}"
    else
        download_url="https://github.com/${GITHUB_REPO}/releases/download/${GITHUB_RELEASE}/${binary_name}"
    fi

    log_info "Downloading from: $download_url"

    local temp_binary="/tmp/lbctl-download-$$"
    
    if ! run curl -fsSL -o "$temp_binary" "$download_url"; then
        log_error "Failed to download lbctl binary"
        log_error "URL: $download_url"
        log_error ""
        log_error "This could mean:"
        log_error "  1. No GitHub release exists yet"
        log_error "  2. The binary name doesn't match the expected format"
        log_error "  3. Network connectivity issues"
        log_error ""
        log_error "To build locally instead:"
        log_error "  git clone https://github.com/${GITHUB_REPO}.git"
        log_error "  cd LibraFlux"
        log_error "  go build -o lbctl ./cmd/lbctl"
        log_error "  sudo ./scripts/deploy.sh"
        exit 1
    fi

    run chmod +x "$temp_binary"
    run mv "$temp_binary" "$LBCTL_BIN"
    
    log_info "Installed lbctl binary to $LBCTL_BIN"
}

# ------------------------------------------------------------------------------
# Configuration Files
# ------------------------------------------------------------------------------
download_config_files() {
    log_step "Downloading configuration files..."

    # Create directories
    run mkdir -p "$LBCTL_CONFIG_DIR"
    run mkdir -p "$LBCTL_CONFIG_DIR/config.d"
    run mkdir -p "$LBCTL_STATE_DIR"
    run mkdir -p "$LBCTL_STATE_DIR/backups"

    local base_url="https://raw.githubusercontent.com/${GITHUB_REPO}/main/dist"

    # Download main config if not present
    if [ ! -f "$LBCTL_CONFIG_DIR/config.yaml" ]; then
        log_info "Downloading example config..."
        if run curl -fsSL -o "$LBCTL_CONFIG_DIR/config.yaml" "${base_url}/config.yaml.example"; then
            log_info "Installed config to $LBCTL_CONFIG_DIR/config.yaml"
        else
            log_warn "Failed to download config.yaml.example - you'll need to create it manually"
        fi
    else
        log_info "Config already exists at $LBCTL_CONFIG_DIR/config.yaml"
    fi

    # Download example service config
    if [ ! -f "$LBCTL_CONFIG_DIR/config.d/example-service.yaml" ]; then
        log_info "Downloading example service config..."
        if run curl -fsSL -o "$LBCTL_CONFIG_DIR/config.d/example-service.yaml" "${base_url}/config.d/example-service.yaml"; then
            log_info "Installed example service config"
        else
            log_warn "Failed to download example-service.yaml"
        fi
    fi

    # Download systemd service
    log_info "Downloading systemd service unit..."
    if run curl -fsSL -o /etc/systemd/system/lbctl.service "${base_url}/lbctl.service"; then
        run systemctl daemon-reload
        log_info "Installed systemd service"
    else
        log_warn "Failed to download lbctl.service"
    fi
}

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------
verify_installation() {
    log_step "Verifying installation..."

    local errors=0
    local warnings=0
    local in_container=false
    
    if is_container; then
        in_container=true
        log_info "(Running in container - some checks adjusted)"
    fi

    echo ""

    # Check IPVS modules (skip in container)
    if $in_container; then
        log_info "⊘ Module check skipped (container)"
    else
        for mod in ip_vs ip_vs_rr ip_vs_wrr; do
            if lsmod | grep -q "^${mod}"; then
                log_info "✓ Module loaded: $mod"
            else
                log_warn "✗ Module not loaded: $mod"
                ((warnings++)) || true
            fi
        done
    fi

    # Check IP forwarding
    if [ "$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null)" = "1" ]; then
        log_info "✓ IP forwarding enabled"
    elif $in_container; then
        log_info "⊘ IP forwarding check skipped (container)"
    else
        log_warn "✗ IP forwarding not enabled"
        ((warnings++)) || true
    fi

    # Check ipvsadm
    if command -v ipvsadm &> /dev/null; then
        log_info "✓ ipvsadm available"
    else
        log_warn "✗ ipvsadm not installed"
        ((warnings++)) || true
    fi

    # Check FRR
    if ! $SKIP_FRR; then
        if command -v vtysh &> /dev/null; then
            log_info "✓ FRR vtysh available"
        else
            log_warn "✗ FRR vtysh not found"
            ((warnings++)) || true
        fi
    fi

    # Check lbctl binary
    if [ -x "$LBCTL_BIN" ]; then
        log_info "✓ lbctl binary installed"
        local version_output
        version_output=$($LBCTL_BIN --version 2>&1 || echo "unknown")
        log_info "  Version: $version_output"
    else
        log_error "✗ lbctl binary not found at $LBCTL_BIN"
        ((errors++)) || true
    fi

    # Check config files
    if [ -f "$LBCTL_CONFIG_DIR/config.yaml" ]; then
        log_info "✓ Config file installed"
    else
        log_warn "✗ Config file not found"
        ((warnings++)) || true
    fi

    # Check systemd service
    if [ -f "/etc/systemd/system/lbctl.service" ]; then
        log_info "✓ Systemd service installed"
    else
        log_warn "✗ Systemd service not found"
        ((warnings++)) || true
    fi

    echo ""
    
    if [ $errors -eq 0 ]; then
        log_info "═══════════════════════════════════════════════════════════"
        log_info "  LibraFlux Installation Complete!"
        log_info "═══════════════════════════════════════════════════════════"
        echo ""
        log_info "Next steps:"
        echo ""
        echo "  1. Configure your node:"
        echo "     ${YELLOW}sudo vi $LBCTL_CONFIG_DIR/config.yaml${NC}"
        echo ""
        echo "     Required changes:"
        echo "       - node.name (unique per node)"
        echo "       - node.role (primary or secondary)"
        echo "       - network.frontend.interface"
        echo "       - network.frontend.vip"
        echo "       - network.backend.interface"
        echo ""
        echo "  2. Define services:"
        echo "     ${YELLOW}sudo vi $LBCTL_CONFIG_DIR/config.d/my-service.yaml${NC}"
        echo ""
        echo "  3. Validate configuration:"
        echo "     ${YELLOW}sudo lbctl validate --config $LBCTL_CONFIG_DIR/config.yaml${NC}"
        echo ""
        echo "  4. Test one-shot application:"
        echo "     ${YELLOW}sudo lbctl apply --config $LBCTL_CONFIG_DIR/config.yaml${NC}"
        echo ""
        echo "  5. Enable daemon mode:"
        echo "     ${YELLOW}sudo systemctl enable lbctl${NC}"
        echo "     ${YELLOW}sudo systemctl start lbctl${NC}"
        echo ""
        echo "  6. Monitor metrics:"
        echo "     ${YELLOW}curl http://localhost:9090/metrics${NC}"
        echo ""
        
        if [ $warnings -gt 0 ]; then
            log_warn "Installation completed with $warnings warning(s)"
            log_warn "Some features may require a reboot or manual configuration"
        fi
    else
        log_error "Installation failed with $errors error(s)"
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------
usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

One-shot installer for LibraFlux on AlmaLinux 8, 9, 10 and compatible systems.

Options:
  --dry-run         Print commands without executing
  --skip-frr        Skip FRR installation (use if you have keepalived)
  --skip-frr-start  Install FRR but don't start it
  -h, --help        Show this help

Environment:
  GITHUB_REPO       GitHub repository (default: YOUR_ORG/LibraFlux)
  GITHUB_RELEASE    Release tag (default: latest)
  LBCTL_BIN         Binary install path (default: /usr/local/bin/lbctl)
  LBCTL_CONFIG_DIR  Config directory (default: /etc/lbctl)

Examples:
  # Standard installation
  curl -fsSL https://raw.githubusercontent.com/malindarathnayake/LibraFlux/main/Deployment/install.sh | sudo bash

  # Skip FRR (if using keepalived)
  curl -fsSL https://raw.githubusercontent.com/malindarathnayake/LibraFlux/main/Deployment/install.sh | sudo bash -s -- --skip-frr

  # Dry-run mode
  curl -fsSL https://raw.githubusercontent.com/malindarathnayake/LibraFlux/main/Deployment/install.sh | sudo bash -s -- --dry-run

EOF
}

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --skip-frr)
                SKIP_FRR=true
                shift
                ;;
            --skip-frr-start)
                SKIP_FRR_START=true
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    echo "═══════════════════════════════════════════════════════════"
    echo "  LibraFlux One-Shot Installer"
    echo "═══════════════════════════════════════════════════════════"
    echo ""

    if $DRY_RUN; then
        log_warn "DRY-RUN MODE - no changes will be made"
        echo ""
    fi

    check_root
    detect_os

    # Verify OS compatibility
    case "$OS_ID" in
        almalinux)
            if [[ "$OS_VERSION_MAJOR" =~ ^(8|9|10)$ ]]; then
                log_info "✓ AlmaLinux $OS_VERSION is supported"
            else
                log_warn "AlmaLinux $OS_VERSION may not be fully tested"
            fi
            ;;
        rocky|rhel|centos)
            if [[ "$OS_VERSION_MAJOR" =~ ^(8|9)$ ]]; then
                log_info "✓ $OS_ID $OS_VERSION is supported"
            else
                log_warn "$OS_ID $OS_VERSION may not be fully tested"
            fi
            ;;
        ubuntu|debian|fedora)
            log_info "✓ $OS_ID $OS_VERSION is supported"
            ;;
        *)
            log_warn "Unknown OS '$OS_ID' - installation may not work correctly"
            ;;
    esac

    echo ""

    install_ipvs_modules
    configure_sysctl
    install_frr
    download_lbctl_binary
    download_config_files
    
    if ! $DRY_RUN; then
        verify_installation
    fi
}

main "$@"

