#!/bin/bash
# deploy.sh - Install lbctl with FRR and configure host for IPVS load balancing
# Usage: ./deploy.sh [--dry-run] [--skip-frr-start] [--skip-frr]
#
# Tested on: AlmaLinux 9, Rocky Linux 9, RHEL 9, Ubuntu 22.04+, Debian 12+

set -euo pipefail

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------
LBCTL_BIN="${LBCTL_BIN:-/usr/local/bin/lbctl}"
LBCTL_CONFIG_DIR="${LBCTL_CONFIG_DIR:-/etc/lbctl}"
LBCTL_STATE_DIR="${LBCTL_STATE_DIR:-/var/lib/lbctl}"
MODULES_LOAD_CONF="/etc/modules-load.d/ipvs.conf"
SYSCTL_CONF="/etc/sysctl.d/90-lbctl.conf"

DRY_RUN=false
SKIP_FRR=false
SKIP_FRR_START=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------
log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

run() {
    if $DRY_RUN; then
        echo "[DRY-RUN] $*"
    else
        "$@"
    fi
}

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_ID="${ID:-unknown}"
        OS_VERSION="${VERSION_ID:-unknown}"
    else
        OS_ID="unknown"
        OS_VERSION="unknown"
    fi
    log_info "Detected OS: $OS_ID $OS_VERSION"
}

check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# IPVS Kernel Modules
# ------------------------------------------------------------------------------
install_ipvs_modules() {
    log_info "Configuring IPVS kernel modules..."

    local modules="ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh"

    # Ensure directory exists
    run mkdir -p "$(dirname "$MODULES_LOAD_CONF")"

    # Create modules-load.d config
    run tee "$MODULES_LOAD_CONF" > /dev/null <<EOF
# lbctl - IPVS kernel modules
ip_vs
ip_vs_rr
ip_vs_wrr
ip_vs_sh
EOF

    # Load modules now
    for mod in $modules; do
        if ! lsmod | grep -q "^${mod}"; then
            log_info "Loading module: $mod"
            run modprobe "$mod" || log_warn "Failed to load $mod (may need reboot)"
        else
            log_info "Module already loaded: $mod"
        fi
    done

    # Install ipvsadm for debugging
    case "$OS_ID" in
        almalinux|rocky|rhel|centos|fedora)
            if ! command -v ipvsadm &> /dev/null; then
                log_info "Installing ipvsadm..."
                run dnf install -y ipvsadm
            fi
            ;;
        ubuntu|debian)
            if ! command -v ipvsadm &> /dev/null; then
                log_info "Installing ipvsadm..."
                run apt-get update
                run apt-get install -y ipvsadm
            fi
            ;;
    esac
}

# ------------------------------------------------------------------------------
# Sysctl Configuration
# ------------------------------------------------------------------------------
configure_sysctl() {
    log_info "Configuring sysctl parameters..."

    # Ensure directory exists
    run mkdir -p "$(dirname "$SYSCTL_CONF")"

    run tee "$SYSCTL_CONF" > /dev/null <<EOF
# lbctl - IPVS and networking tuning
# Generated by deploy.sh

# Enable IP forwarding (required for IPVS)
net.ipv4.ip_forward = 1

# IPVS connection tracking (required for NAT mode)
net.ipv4.vs.conntrack = 1

# Connection table size (tune for expected connections)
net.ipv4.vs.conn_tab_bits = 12

# Expire quiescent connections (backends set to weight 0)
net.ipv4.vs.expire_quiescent_template = 1

# Timeouts (seconds)
net.ipv4.vs.timeout_tcp = 900
net.ipv4.vs.timeout_tcpfin = 120
net.ipv4.vs.timeout_udp = 300

# Ignore ARP for VIPs on non-VIP interfaces (for DR mode)
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2

# Conntrack tuning
net.netfilter.nf_conntrack_max = 1048576
EOF

    # Apply sysctl
    run sysctl --system > /dev/null 2>&1 || log_warn "Some sysctl parameters may not apply until reboot"
}

# ------------------------------------------------------------------------------
# FRR Installation
# ------------------------------------------------------------------------------
install_frr() {
    if $SKIP_FRR; then
        log_info "Skipping FRR installation (--skip-frr)"
        return
    fi

    log_info "Installing FRR for VRRP support..."

    case "$OS_ID" in
        almalinux|rocky|rhel|centos)
            # Enable EPEL if not present
            if ! rpm -q epel-release &> /dev/null; then
                log_info "Installing EPEL repository..."
                run dnf install -y epel-release
            fi
            
            # Install FRR (frr-pythontools may not exist in all repos)
            if ! rpm -q frr &> /dev/null; then
                run dnf install -y frr
                run dnf install -y frr-pythontools 2>/dev/null || log_warn "frr-pythontools not available (optional)"
            else
                log_info "FRR already installed"
            fi
            ;;

        fedora)
            if ! rpm -q frr &> /dev/null; then
                run dnf install -y frr
                run dnf install -y frr-pythontools 2>/dev/null || log_warn "frr-pythontools not available (optional)"
            else
                log_info "FRR already installed"
            fi
            ;;

        ubuntu|debian)
            if ! dpkg -l frr &> /dev/null 2>&1; then
                # Add FRR repository for latest version
                run apt-get update
                run apt-get install -y curl gnupg lsb-release

                # FRR official repo
                curl -s https://deb.frrouting.org/frr/keys.gpg | gpg --dearmor -o /usr/share/keyrings/frr.gpg 2>/dev/null || true

                CODENAME=$(lsb_release -cs)
                echo "deb [signed-by=/usr/share/keyrings/frr.gpg] https://deb.frrouting.org/frr $CODENAME frr-stable" | \
                    tee /etc/apt/sources.list.d/frr.list > /dev/null

                run apt-get update
                run apt-get install -y frr frr-pythontools
            else
                log_info "FRR already installed"
            fi
            ;;

        *)
            log_warn "Unknown OS '$OS_ID' - skipping FRR installation"
            log_warn "Please install FRR manually: https://docs.frrouting.org/en/latest/installation.html"
            return
            ;;
    esac

    # Enable VRRP daemon
    configure_frr_daemons
}

configure_frr_daemons() {
    log_info "Enabling FRR VRRP daemon..."

    local frr_daemons="/etc/frr/daemons"
    
    if [ -f "$frr_daemons" ]; then
        # Enable vrrpd
        if grep -q "^vrrpd=no" "$frr_daemons"; then
            run sed -i 's/^vrrpd=no/vrrpd=yes/' "$frr_daemons"
            log_info "Enabled vrrpd in $frr_daemons"
        elif grep -q "^vrrpd=yes" "$frr_daemons"; then
            log_info "vrrpd already enabled"
        else
            echo "vrrpd=yes" | run tee -a "$frr_daemons" > /dev/null
        fi
    else
        log_warn "FRR daemons file not found at $frr_daemons"
    fi

    # Start FRR
    if ! $SKIP_FRR_START; then
        log_info "Starting FRR service..."
        run systemctl enable frr
        run systemctl restart frr
    else
        log_info "Skipping FRR start (--skip-frr-start)"
    fi
}

# ------------------------------------------------------------------------------
# lbctl Installation
# ------------------------------------------------------------------------------
install_lbctl() {
    log_info "Setting up lbctl directories..."

    # Create directories
    run mkdir -p "$LBCTL_CONFIG_DIR"
    run mkdir -p "$LBCTL_CONFIG_DIR/config.d"
    run mkdir -p "$LBCTL_STATE_DIR"
    run mkdir -p "$LBCTL_STATE_DIR/backups"

    # Copy example config if not present
    if [ ! -f "$LBCTL_CONFIG_DIR/config.yaml" ]; then
        if [ -f "dist/config.yaml.example" ]; then
            run cp dist/config.yaml.example "$LBCTL_CONFIG_DIR/config.yaml"
            log_info "Installed example config to $LBCTL_CONFIG_DIR/config.yaml"
        fi
    else
        log_info "Config already exists at $LBCTL_CONFIG_DIR/config.yaml"
    fi

    # Copy example service configs
    if [ -d "dist/config.d" ]; then
        for f in dist/config.d/*.yaml; do
            [ -f "$f" ] || continue
            local basename=$(basename "$f")
            if [ ! -f "$LBCTL_CONFIG_DIR/config.d/$basename" ]; then
                run cp "$f" "$LBCTL_CONFIG_DIR/config.d/"
                log_info "Installed example: config.d/$basename"
            fi
        done
    fi

    # Install binary if present in current directory
    if [ -f "./lbctl" ]; then
        run install -m 0755 ./lbctl "$LBCTL_BIN"
        log_info "Installed lbctl binary to $LBCTL_BIN"
    elif [ -f "./bin/lbctl" ]; then
        run install -m 0755 ./bin/lbctl "$LBCTL_BIN"
        log_info "Installed lbctl binary to $LBCTL_BIN"
    else
        log_warn "No lbctl binary found - build with 'make build' first"
    fi

    # Install systemd service
    if [ -f "dist/lbctl.service" ]; then
        run cp dist/lbctl.service /etc/systemd/system/
        run systemctl daemon-reload
        log_info "Installed systemd service (enable with: systemctl enable lbctl)"
    fi
}

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------
is_container() {
    # Detect if running in a container
    [ -f /.dockerenv ] || grep -q 'docker\|lxc\|containerd' /proc/1/cgroup 2>/dev/null
}

verify_installation() {
    log_info "Verifying installation..."

    local errors=0
    local in_container=false
    
    if is_container; then
        in_container=true
        log_info "(Running in container - some checks adjusted)"
    fi

    # Check IPVS modules (skip in container - modules are host-level)
    if $in_container; then
        log_info "⊘ Module check skipped (container)"
    else
        for mod in ip_vs ip_vs_rr ip_vs_wrr; do
            if lsmod | grep -q "^${mod}"; then
                log_info "✓ Module loaded: $mod"
            else
                log_warn "✗ Module not loaded: $mod"
                ((errors++)) || true
            fi
        done
    fi

    # Check IP forwarding
    if [ "$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null)" = "1" ]; then
        log_info "✓ IP forwarding enabled"
    elif $in_container; then
        log_info "⊘ IP forwarding check skipped (container)"
    else
        log_warn "✗ IP forwarding not enabled"
        ((errors++)) || true
    fi

    # Check ipvsadm
    if command -v ipvsadm &> /dev/null; then
        log_info "✓ ipvsadm available"
    else
        log_warn "✗ ipvsadm not installed"
        ((errors++)) || true
    fi

    # Check FRR
    if ! $SKIP_FRR; then
        if command -v vtysh &> /dev/null; then
            log_info "✓ FRR vtysh available"
        else
            log_warn "✗ FRR vtysh not found"
            ((errors++)) || true
        fi
    fi

    # Check lbctl binary (skip in container test - binary built separately)
    if [ -x "$LBCTL_BIN" ]; then
        log_info "✓ lbctl binary installed"
        $LBCTL_BIN --version 2>/dev/null || $LBCTL_BIN --help | head -1
    elif $in_container; then
        log_info "⊘ Binary check skipped (container test)"
    else
        log_warn "✗ lbctl binary not found at $LBCTL_BIN"
        ((errors++)) || true
    fi

    # Check config files
    if [ -f "$LBCTL_CONFIG_DIR/config.yaml" ]; then
        log_info "✓ Config file installed"
    else
        log_warn "✗ Config file not found"
        ((errors++)) || true
    fi

    # Check systemd service
    if [ -f "/etc/systemd/system/lbctl.service" ]; then
        log_info "✓ Systemd service installed"
    else
        log_warn "✗ Systemd service not found"
        ((errors++)) || true
    fi

    echo ""
    if [ $errors -eq 0 ]; then
        log_info "Installation complete! Next steps:"
        echo "  1. Edit config: $LBCTL_CONFIG_DIR/config.yaml"
        echo "  2. Validate:    lbctl validate --config $LBCTL_CONFIG_DIR/config.yaml"
        echo "  3. Apply:       lbctl apply --config $LBCTL_CONFIG_DIR/config.yaml"
        echo "  4. Daemon:      systemctl start lbctl"
    else
        log_warn "Installation completed with $errors warning(s)"
        log_warn "Some features may require a reboot or manual configuration"
    fi
}

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------
usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Install lbctl with FRR and configure host for IPVS load balancing.

Options:
  --dry-run         Print commands without executing
  --skip-frr        Skip FRR installation (use if you have keepalived)
  --skip-frr-start  Install FRR but don't start it (for Docker testing)
  -h, --help        Show this help

Environment:
  LBCTL_BIN         Binary install path (default: /usr/local/bin/lbctl)
  LBCTL_CONFIG_DIR  Config directory (default: /etc/lbctl)
EOF
}

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --skip-frr)
                SKIP_FRR=true
                shift
                ;;
            --skip-frr-start)
                SKIP_FRR_START=true
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    echo "========================================"
    echo "  lbctl Deployment Script"
    echo "========================================"
    echo ""

    if $DRY_RUN; then
        log_warn "DRY-RUN MODE - no changes will be made"
        echo ""
    fi

    check_root
    detect_os

    install_ipvs_modules
    configure_sysctl
    install_frr
    install_lbctl
    
    if ! $DRY_RUN; then
        verify_installation
    fi
}

main "$@"

